// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/27/2025, 11:58:54 AM
const configMerger = require("/home/ubuntu/repos/aifeeds/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.27.4/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/ubuntu/repos/aifeeds/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/plugins/**/*.{js,ts,mjs}","/home/ubuntu/repos/aifeeds/composables/**/*.{js,ts,mjs}","/home/ubuntu/repos/aifeeds/utils/**/*.{js,ts,mjs}","/home/ubuntu/repos/aifeeds/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/repos/aifeeds/app.config.{js,ts,mjs}"] } }));

module.exports = config
